require("dotenv").config();
const express = require("express");
const PDFDocument = require("pdfkit");
const path = require("path");

const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.static(path.join(__dirname, "public")));

function randInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function buildWorksheetQuestions({ count = 30, op = "+", max = 20 }) {
  const qs = [];

  for (let i = 0; i < count; i++) {
    let a = randInt(1, max);
    let b = randInt(1, max);

    if (op === "-") {
      // keep non-negative
      if (b > a) [a, b] = [b, a];
    }

    if (op === "/") {
      // clean division: a ÷ b = whole number
      b = randInt(1, Math.max(2, Math.floor(max / 2)));
      const k = randInt(1, Math.max(2, Math.floor(max / b)));
      a = b * k;
    }

    qs.push({ a, b, op });
  }

  return qs;
}

app.get("/api/worksheet.pdf", (req, res) => {
  const op = (req.query.op || "+").toString();
  const max = Math.min(500, Math.max(5, parseInt(req.query.max || "20", 10)));
  const count = Math.min(120, Math.max(10, parseInt(req.query.count || "30", 10)));

  const titleMap = {
    "+": "Addition Practice",
    "-": "Subtraction Practice",
    "*": "Multiplication Practice",
    "/": "Division Practice",
  };

  const title = titleMap[op] || "Math Practice";
  const subtitle = "Name: ____________________    Date: ____________________";
  const questions = buildWorksheetQuestions({ count, op, max });
  const answers = questions.map((q) =>
    op === "+" ? q.a + q.b :
    op === "-" ? q.a - q.b :
    op === "*" ? q.a * q.b :
    op === "/" ? q.a / q.b :
    ""
  );
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", 'attachment; filename="worksheet.pdf"');

  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 54, bottom: 54, left: 54, right: 54 },
    info: { Title: title, Author: "Yellowbird v1" },
  });

  doc.pipe(res);

  // Header
  doc.font("Helvetica-Bold").fontSize(18).text(title, { align: "center" });
  doc.moveDown(0.4);
  doc.font("Helvetica").fontSize(12).text(subtitle, { align: "left" });
  doc.moveDown(1);

  // Layout: 2 columns, NO wrapping (prevents stacking)
  const pageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const cols = 2;
  const colGap = 40;
  const rowGap = 34;

  const colWidth = (pageWidth - colGap * (cols - 1)) / cols;
  const startX = doc.page.margins.left;
  const startY = doc.y;

  doc.font("Helvetica").fontSize(16);

  const symbol = op === "*" ? "×" : op === "/" ? "÷" : op;

  for (let idx = 0; idx < questions.length; idx++) {
    const q = questions[idx];

    const c = idx % cols;
    const r = Math.floor(idx / cols);

    const x = startX + c * (colWidth + colGap);
    const y = startY + r * rowGap;

    // label
    doc.text(`${idx + 1})`, x, y, { width: 34, lineBreak: false });

    // question text (NO wrapping)
    const expr = `${q.a} ${symbol} ${q.b} =`;
        const answer =
      op === "+" ? q.a + q.b :
      op === "-" ? q.a - q.b :
      op === "*" ? q.a * q.b :
      op === "/" ? q.a / q.b :
      "";
    doc.text(expr, x + 34, y, { width: colWidth - 34, lineBreak: false });

    // draw a real answer line
    const lineStartX = x + 34 + doc.widthOfString(expr) + 10;
    const lineEndX = x + colWidth - 6;
    const lineY = y + 18;

    doc
      .moveTo(Math.min(lineStartX, lineEndX - 40), lineY)
      .lineTo(lineEndX, lineY)
      .stroke();
  }

    // Footer (keep INSIDE margins to avoid auto-blank page)
  doc.fontSize(9).fillColor("#444");
  doc.text(
    "Generated by Yellowbird v1",
    doc.page.margins.left,
    doc.page.height - doc.page.margins.bottom - 12,
    { align: "left", lineBreak: false }
  );
  // --- Page 2: Answer Key ---
  doc.addPage();

  doc.fillColor("#000");
  doc.font("Helvetica-Bold").fontSize(18).text(`${title} — Answer Key`, { align: "center" });
  doc.moveDown(0.6);

  doc.font("Helvetica").fontSize(12).text(subtitle, { align: "left" });
  doc.moveDown(1);

  const keyPageWidth =
    doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const keyCols = 3;
  const keyColGap = 24;
  const keyRowGap = 18;

  const keyColWidth = (keyPageWidth - keyColGap * (keyCols - 1)) / keyCols;
  const keyStartX = doc.page.margins.left;
  const keyStartY = doc.y;

  doc.font("Helvetica").fontSize(12);

  for (let i = 0; i < questions.length; i++) {
    const c = i % keyCols;
    const r = Math.floor(i / keyCols);

    const x = keyStartX + c * (keyColWidth + keyColGap);
    const y = keyStartY + r * keyRowGap;

    const q = questions[i];
    const ans = answers[i];
    const sym = op === "*" ? "×" : op === "/" ? "÷" : op;

    const line = `${i + 1})  ${q.a} ${sym} ${q.b} = ${ans}`;
    doc.text(line, x, y, { width: keyColWidth, lineBreak: false });
  }
  doc.end();
});

app.listen(PORT, () => {
  console.log(`Yellowbird v1 running → http://localhost:${PORT}`);
});