const grade6Catalog = [
  {
    id: "g6_pattern_rules",
    title: "Pattern Rules",
    shortTitle: "Pattern Rules",
    subject: "Math",
    grades: ["grade6"],
    gradeLabels: ["Grade 6"],
    domain: "Patterning & Algebra",
    skillKey: "patterning_and_algebra",
    worksheetFamily: "relational_thinking",
    activityTypes: ["patterning_and_algebra"],
    templateId: "equation_practice",
    status: "partial",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["patterns", "rules", "algebra", "grade 6"],
    curriculumTags: ["C1"],
    description: "Students identify, extend, and describe pattern rules."
  },
  {
    id: "g6_input_output_tables",
    title: "Input-Output Tables",
    shortTitle: "Input-Output Tables",
    subject: "Math",
    grades: ["grade6"],
    gradeLabels: ["Grade 6"],
    domain: "Patterning & Algebra",
    skillKey: "patterning_and_algebra",
    worksheetFamily: "relational_thinking",
    activityTypes: ["patterning_and_algebra"],
    templateId: "equation_practice",
    status: "planned",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["input output", "tables", "algebra", "grade 6"],
    curriculumTags: ["C1"],
    description: "Students analyze and complete input-output tables."
  },
  {
    id: "g6_fraction_equivalence_review",
    title: "Fraction Equivalence Review",
    shortTitle: "Fraction Equivalence",
    subject: "Math",
    grades: ["grade6"],
    gradeLabels: ["Grade 6"],
    domain: "Fractions",
    skillKey: "fraction_equivalence",
    worksheetFamily: "relational_thinking",
    activityTypes: ["fraction_equivalence"],
    templateId: "equation_practice",
    status: "partial",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["fractions", "equivalence", "grade 6"],
    curriculumTags: ["B1"],
    description: "Students review and apply equivalent fraction reasoning."
  },
  {
    id: "g6_graph_interpretation",
    title: "Graph Interpretation",
    shortTitle: "Graph Interpretation",
    subject: "Math",
    grades: ["grade6"],
    gradeLabels: ["Grade 6"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["interpret_data", "graph_questions"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["graphs", "interpretation", "grade 6"],
    curriculumTags: ["D1"],
    description: "Students interpret graphs and justify conclusions using data."
  }
];

module.exports = grade6Catalog;