const grade4Catalog = [
  {
    id: "g4_multiplication_fact_fluency",
    title: "Multiplication Fact Fluency",
    shortTitle: "Multiplication Facts",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["math.multiplication.basic"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["multiplication", "facts", "fluency", "grade 4"],
    curriculumTags: ["B2"],
    description: "Students practise multiplication fact fluency."
  },
  {
    id: "g4_missing_factors",
    title: "Missing Factors",
    shortTitle: "Missing Factors",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["missing_factor"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["missing factor", "multiplication", "grade 4"],
    curriculumTags: ["B2"],
    description: "Students solve multiplication equations with a missing factor."
  },
  {
    id: "g4_array_interpretation",
    title: "Array Interpretation",
    shortTitle: "Arrays",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_foundations",
    worksheetFamily: "visual_models",
    activityTypes: ["arrays"],
    templateId: "model_interpretation",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["arrays", "multiplication", "grade 4"],
    curriculumTags: ["B2"],
    description: "Students interpret arrays and connect them to multiplication equations."
  },
  {
    id: "g4_equal_groups_interpretation",
    title: "Equal Groups Interpretation",
    shortTitle: "Equal Groups",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_foundations",
    worksheetFamily: "visual_models",
    activityTypes: ["equal_groups"],
    templateId: "model_interpretation",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["equal groups", "multiplication", "grade 4"],
    curriculumTags: ["B2"],
    description: "Students use equal-group models to reason about multiplication."
  },
  {
    id: "g4_expanded_form_large_numbers",
    title: "Expanded Form with Large Numbers",
    shortTitle: "Expanded Form",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Place Value",
    skillKey: "place_value_representation",
    worksheetFamily: "representation",
    activityTypes: ["expanded_form"],
    templateId: "representation",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["expanded form", "large numbers", "grade 4"],
    curriculumTags: ["B1"],
    description: "Students write larger numbers in expanded form."
  },
  {
    id: "g4_standard_form_large_numbers",
    title: "Standard Form with Large Numbers",
    shortTitle: "Standard Form",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Place Value",
    skillKey: "place_value_representation",
    worksheetFamily: "representation",
    activityTypes: ["standard_form"],
    templateId: "representation",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["standard form", "large numbers", "grade 4"],
    curriculumTags: ["B1"],
    description: "Students convert representations into standard form with larger numbers."
  },
  {
    id: "g4_read_and_interpret_graphs",
    title: "Read and Interpret Graphs",
    shortTitle: "Interpret Graphs",
    subject: "Math",
    grades: ["grade4"],
    gradeLabels: ["Grade 4"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["read_graph", "interpret_data"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["graphs", "interpret data", "grade 4"],
    curriculumTags: ["D1"],
    description: "Students read graphs and answer interpretation questions in context."
  }
];

module.exports = grade4Catalog;