const grade5Catalog = [
  {
    id: "g5_fraction_equivalence",
    title: "Fraction Equivalence",
    shortTitle: "Fraction Equivalence",
    subject: "Math",
    grades: ["grade5"],
    gradeLabels: ["Grade 5"],
    domain: "Fractions",
    skillKey: "fraction_equivalence",
    worksheetFamily: "relational_thinking",
    activityTypes: ["fraction_equivalence"],
    templateId: "equation_practice",
    status: "partial",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["fractions", "equivalence", "grade 5"],
    curriculumTags: ["B1"],
    description: "Students identify and generate equivalent fractions."
  },
  {
    id: "g5_fraction_number_line",
    title: "Fractions on a Number Line",
    shortTitle: "Fraction Number Line",
    subject: "Math",
    grades: ["grade5"],
    gradeLabels: ["Grade 5"],
    domain: "Fractions",
    skillKey: "fraction_magnitude",
    worksheetFamily: "visual_models",
    activityTypes: ["number_line_identify"],
    templateId: "visual_model",
    status: "planned",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["fractions", "number line", "grade 5"],
    curriculumTags: ["B1"],
    description: "Students locate and compare fractions on number lines."
  },
  {
    id: "g5_multiplication_fact_review",
    title: "Multiplication Fact Review",
    shortTitle: "Fact Review",
    subject: "Math",
    grades: ["grade5"],
    gradeLabels: ["Grade 5"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["math.multiplication.basic"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["multiplication", "fact review", "grade 5"],
    curriculumTags: ["B2"],
    description: "Students review multiplication facts for fluency and retention."
  },
  {
    id: "g5_interpret_graphs",
    title: "Interpret Graphs",
    shortTitle: "Interpret Graphs",
    subject: "Math",
    grades: ["grade5"],
    gradeLabels: ["Grade 5"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["interpret_data", "graph_questions"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["graphs", "interpret", "grade 5"],
    curriculumTags: ["D1"],
    description: "Students interpret graph displays and answer comparison questions."
  },
  {
    id: "g5_complete_graphs",
    title: "Complete Graphs",
    shortTitle: "Complete Graphs",
    subject: "Math",
    grades: ["grade5"],
    gradeLabels: ["Grade 5"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["complete_graph"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["graphs", "complete graph", "grade 5"],
    curriculumTags: ["D1"],
    description: "Students use provided data to complete graph displays."
  }
];

module.exports = grade5Catalog;