const grade2Catalog = [
  {
    id: "g2_base_ten_blocks_representation",
    title: "Base Ten Blocks Representation",
    shortTitle: "Base Ten Blocks",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Place Value",
    skillKey: "place_value_representation",
    worksheetFamily: "visual_models",
    activityTypes: ["base_ten_blocks"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["base ten blocks", "place value", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students interpret base ten block models and write matching numbers."
  },
  {
    id: "g2_expanded_form_to_100",
    title: "Expanded Form to 100",
    shortTitle: "Expanded Form",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Place Value",
    skillKey: "place_value_representation",
    worksheetFamily: "representation",
    activityTypes: ["expanded_form"],
    templateId: "representation",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    generatorOptions: { minA: 10, maxA: 100 },
    tags: ["expanded form", "to 100", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students write numbers in expanded form."
  },
  {
    id: "g2_standard_form_to_100",
    title: "Standard Form to 100",
    shortTitle: "Standard Form",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Place Value",
    skillKey: "place_value_representation",
    worksheetFamily: "representation",
    activityTypes: ["standard_form"],
    generatorOptions: { minA: 10, maxA: 100 },
    templateId: "representation",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["standard form", "to 100", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students convert representations into standard form."
  },
  {
    id: "g2_compare_numbers_to_100",
    title: "Compare Numbers to 100",
    shortTitle: "Compare Numbers",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Place Value",
    skillKey: "number_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["compare_numbers"],
    generatorOptions: { minA: 0, maxA: 100 },
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["compare", "numbers", "to 100", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students compare two-digit numbers using symbols and reasoning."
  },
  {
    id: "g2_addition_fluency_within_100",
    title: "Addition Fluency Within 100",
    shortTitle: "Addition Fluency",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["math.addition.basic"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["addition", "fluency", "within 100", "grade 2"],
    curriculumTags: ["B2"],
    description: "Students practise addition fluency with age-appropriate number ranges."
  },
  {
    id: "g2_subtraction_fluency_within_100",
    title: "Subtraction Fluency Within 100",
    shortTitle: "Subtraction Fluency",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["related_subtraction"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["subtraction", "fluency", "within 100", "grade 2"],
    curriculumTags: ["B2"],
    description: "Students practise subtraction fluency with age-appropriate number ranges."
  },
  {
    id: "g2_missing_addends_within_100",
    title: "Missing Addends Within 100",
    shortTitle: "Missing Addends",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["missing_addend"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["missing addend", "within 100", "grade 2"],
    curriculumTags: ["B2"],
    description: "Students solve equations with a missing addend."
  },
  {
    id: "g2_addition_word_problems_within_100",
    title: "Addition Word Problems Within 100",
    shortTitle: "Addition Word Problems",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_application",
    worksheetFamily: "problem_solving",
    activityTypes: ["word_problems"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["addition", "word problems", "within 100", "grade 2"],
    curriculumTags: ["B2"],
    description: "Students solve addition word problems using equations, drawings, or models."
  },
  {
    id: "g2_skip_counting_by_2",
    title: "Skip Counting by 2",
    shortTitle: "Skip Counting by 2",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Number Sense",
    skillKey: "counting_patterns",
    worksheetFamily: "daily_review",
    activityTypes: ["skip_counting"],
    generatorOptions: {
      step: 2
    },
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["skip counting", "by 2", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students complete skip-counting patterns by 2."
  },
  {
    id: "g2_skip_counting_by_5",
    title: "Skip Counting by 5",
    shortTitle: "Skip Counting by 5",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Number Sense",
    skillKey: "counting_patterns",
    worksheetFamily: "daily_review",
    activityTypes: ["skip_counting"],
    generatorOptions: {
      step: 5
    },
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["skip counting", "by 5", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students complete skip-counting patterns by 5."
  },
  {
    id: "g2_skip_counting_by_10",
    title: "Skip Counting by 10",
    shortTitle: "Skip Counting by 10",
    subject: "Math",
    grades: ["grade2"],
    gradeLabels: ["Grade 2"],
    domain: "Number Sense",
    skillKey: "counting_patterns",
    worksheetFamily: "daily_review",
    activityTypes: ["skip_counting"],
    generatorOptions: {
      step: 10
    },
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["skip counting", "by 10", "grade 2"],
    curriculumTags: ["B1"],
    description: "Students complete skip-counting patterns by 10."
  }
];

module.exports = grade2Catalog;
