const grade1Catalog = [
  {
    id: "g1_compare_numbers_to_20",
    title: "Compare Numbers to 20",
    shortTitle: "Compare Numbers to 20",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Number Sense",
    skillKey: "number_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["compare_numbers"],
    generatorOptions: { minA: 0, maxA: 20 },
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["compare", "numbers", "to 20", "greater than", "less than"],
    curriculumTags: ["B1"],
    description: "Students compare numbers and insert the correct symbol."
  },
  {
    id: "g1_number_word_match_to_50",
    title: "Number Word Match to 50",
    shortTitle: "Number Word Match",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Number Sense",
    skillKey: "number_representation",
    worksheetFamily: "representation",
    activityTypes: ["number_word_match"],
    generatorOptions: { minA: 0, maxA: 50 },
    templateId: "matching",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["number words", "match", "to 50", "grade 1"],
    curriculumTags: ["B1"],
    description: "Students match numerals and number words."
  },
  {
    id: "g1_number_line_identify_to_20",
    title: "Identify Numbers on a Number Line to 20",
    shortTitle: "Number Line Identify",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Number Sense",
    skillKey: "number_magnitude",
    worksheetFamily: "visual_models",
    activityTypes: ["number_line_identify"],
    generatorOptions: {
      minA: 0,
      maxA: 20
    },
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["number line", "identify", "to 20", "grade 1"],
    curriculumTags: ["B1"],
    description: "Students identify and read numbers on a number line."
  },
  {
    id: "g1_addition_facts_within_20",
    title: "Addition Facts Within 20",
    shortTitle: "Addition Facts",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["math.addition.basic"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["addition", "facts", "within 20", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students practise basic addition facts within 20."
  },
  {
    id: "g1_subtraction_facts_within_20",
    title: "Subtraction Facts Within 20",
    shortTitle: "Subtraction Facts",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["related_subtraction"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["subtraction", "facts", "within 20", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students practise basic subtraction facts within 20."
  },
  {
    id: "g1_missing_addends_within_20",
    title: "Missing Addends Within 20",
    shortTitle: "Missing Addends",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_facts",
    worksheetFamily: "relational_thinking",
    activityTypes: ["missing_addend"],
    generatorOptions: { maxTotal: 20 },
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["missing addend", "within 20", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students fill in the missing addend in basic equations."
  },
  {
    id: "g1_fact_families_within_20",
    title: "Fact Families Within 20",
    shortTitle: "Fact Families",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["fact_family"],
    templateId: "matching",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["fact families", "addition", "subtraction", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students connect related addition and subtraction facts."
  },
  {
    id: "g1_addition_word_problems",
    title: "Addition Word Problems",
    shortTitle: "Addition Word Problems",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_subtraction_application",
    worksheetFamily: "problem_solving",
    activityTypes: ["word_problems"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["addition", "word problems", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students solve simple addition word problems with visual or equation support."
  },
  {
    id: "g1_ten_frame_addition_within_10",
    title: "Ten Frame Addition Within 10",
    shortTitle: "Ten Frame Addition",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_strategies",
    worksheetFamily: "visual_models",
    activityTypes: ["ten_frame"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["ten frame", "addition", "within 10", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students use ten frames to solve addition problems."
  },
  {
    id: "g1_addition_on_number_line_to_20",
    title: "Addition on a Number Line to 20",
    shortTitle: "Addition on Number Line",
    subject: "Math",
    grades: ["grade1"],
    gradeLabels: ["Grade 1"],
    domain: "Addition & Subtraction",
    skillKey: "addition_strategies",
    worksheetFamily: "visual_models",
    activityTypes: ["number_line_identify"],
    templateId: "visual_model",
    status: "partial",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["number line", "addition", "to 20", "grade 1"],
    curriculumTags: ["B2"],
    description: "Students use number lines to model and solve addition problems."
  }
];

module.exports = grade1Catalog;
