const grade3Catalog = [
  {
    id: "g3_multiplication_arrays",
    title: "Multiplication with Arrays",
    shortTitle: "Arrays",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_foundations",
    worksheetFamily: "visual_models",
    activityTypes: ["arrays"],
    templateId: "model_interpretation",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["arrays", "multiplication", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students interpret arrays and connect them to multiplication equations."
  },
  {
    id: "g3_equal_groups_multiplication",
    title: "Equal Groups for Multiplication",
    shortTitle: "Equal Groups",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_foundations",
    worksheetFamily: "visual_models",
    activityTypes: ["equal_groups"],
    templateId: "model_interpretation",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["equal groups", "multiplication", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students model multiplication using equal groups."
  },
  {
    id: "g3_multiplication_facts",
    title: "Multiplication Facts",
    shortTitle: "Multiplication Facts",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_facts",
    worksheetFamily: "fact_fluency",
    activityTypes: ["math.multiplication.basic"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["multiplication", "facts", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students practise multiplication fact fluency."
  },
  {
    id: "g3_missing_factors",
    title: "Missing Factors",
    shortTitle: "Missing Factors",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["missing_factor"],
    templateId: "fluency_grid",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["missing factor", "multiplication", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students solve multiplication equations with a missing factor."
  },
  {
    id: "g3_fact_families_multiplication_division",
    title: "Multiplication and Division Fact Families",
    shortTitle: "Fact Families",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "multiplication_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["fact_family"],
    templateId: "matching",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["fact families", "multiplication", "division", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students connect related multiplication and division facts."
  },
  {
    id: "g3_equal_sharing_division",
    title: "Equal Sharing Division",
    shortTitle: "Equal Sharing",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Multiplication & Division",
    skillKey: "division_foundations",
    worksheetFamily: "visual_models",
    activityTypes: ["equal_groups"],
    templateId: "model_interpretation",
    status: "partial",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["division", "equal sharing", "grade 3"],
    curriculumTags: ["B2"],
    description: "Students interpret equal-sharing situations as division."
  },
  {
    id: "g3_read_a_graph",
    title: "Read a Graph",
    shortTitle: "Read a Graph",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["read_graph"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["graph", "read graph", "grade 3"],
    curriculumTags: ["D1"],
    description: "Students read a graph and answer questions about the data."
  },
  {
    id: "g3_complete_a_graph",
    title: "Complete a Graph",
    shortTitle: "Complete a Graph",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["complete_graph"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 12,
    hasAnswerKey: true,
    tags: ["graph", "complete graph", "grade 3"],
    curriculumTags: ["D1"],
    description: "Students use provided data to complete a graph."
  },
  {
    id: "g3_interpret_data",
    title: "Interpret Data",
    shortTitle: "Interpret Data",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["interpret_data"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["interpret data", "graphing", "grade 3"],
    curriculumTags: ["D1"],
    description: "Students interpret data displays and answer questions in context."
  },
  {
    id: "g3_match_data_to_graph",
    title: "Match Data to Graph",
    shortTitle: "Match Data to Graph",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["match_data_to_graph"],
    templateId: "matching",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["match", "data", "graph", "grade 3"],
    curriculumTags: ["D1"],
    description: "Students match datasets to the correct graph."
  },
  {
    id: "g3_graph_questions",
    title: "Graph Questions",
    shortTitle: "Graph Questions",
    subject: "Math",
    grades: ["grade3"],
    gradeLabels: ["Grade 3"],
    domain: "Data & Graphing",
    skillKey: "data_display_graphing",
    worksheetFamily: "data_graphing",
    activityTypes: ["graph_questions"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "medium",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["graph questions", "data", "grade 3"],
    curriculumTags: ["D1"],
    description: "Students answer comparison and interpretation questions based on graph data."
  }
];

module.exports = grade3Catalog;