const kindergartenCatalog = [
  {
    id: "k_counting_collections_to_10",
    title: "Counting Collections to 10",
    shortTitle: "Counting Collections",
    subject: "Math",
    grades: ["kindergarten"],
    gradeLabels: ["Kindergarten"],
    domain: "Number Sense",
    skillKey: "early_number_sense",
    worksheetFamily: "visual_models",
    activityTypes: ["ten_frame"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["counting", "collections", "to 10", "ten frame", "kindergarten"],
    curriculumTags: ["B1"],
    description: "Students count objects or ten-frame representations and write the total."
  },
  {
    id: "k_ten_frame_counting_to_10",
    title: "Ten Frame Counting to 10",
    shortTitle: "Ten Frame Counting",
    subject: "Math",
    grades: ["kindergarten"],
    gradeLabels: ["Kindergarten"],
    domain: "Number Sense",
    skillKey: "early_number_sense",
    worksheetFamily: "visual_models",
    activityTypes: ["ten_frame"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 10,
    hasAnswerKey: true,
    tags: ["ten frame", "counting", "to 10", "kindergarten"],
    curriculumTags: ["B1"],
    description: "Students use ten frames to identify quantities quickly and accurately."
  },
  {
    id: "k_compare_sets",
    title: "Compare Sets",
    shortTitle: "Compare Sets",
    subject: "Math",
    grades: ["kindergarten"],
    gradeLabels: ["Kindergarten"],
    domain: "Number Sense",
    skillKey: "number_relationships",
    worksheetFamily: "relational_thinking",
    activityTypes: ["compare_numbers"],
    templateId: "equation_practice",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["compare", "sets", "more", "less", "equal", "kindergarten"],
    curriculumTags: ["B1"],
    description: "Students compare quantities and identify which set has more, less, or the same."
  },
  {
    id: "k_number_word_match_to_10",
    title: "Number Word Match to 10",
    shortTitle: "Number Word Match",
    subject: "Math",
    grades: ["kindergarten"],
    gradeLabels: ["Kindergarten"],
    domain: "Number Sense",
    skillKey: "number_representation",
    worksheetFamily: "representation",
    activityTypes: ["number_word_match"],
    templateId: "matching",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["number words", "match", "to 10", "kindergarten"],
    curriculumTags: ["B1"],
    description: "Students match numerals to number words."
  },
  {
    id: "k_numbers_on_number_line_to_10",
    title: "Numbers on a Number Line to 10",
    shortTitle: "Number Line to 10",
    subject: "Math",
    grades: ["kindergarten"],
    gradeLabels: ["Kindergarten"],
    domain: "Number Sense",
    skillKey: "number_magnitude",
    worksheetFamily: "visual_models",
    activityTypes: ["number_line_identify"],
    templateId: "visual_model",
    status: "ready",
    difficulty: "easy",
    estimatedTimeMinutes: 8,
    hasAnswerKey: true,
    tags: ["number line", "to 10", "identify", "kindergarten"],
    curriculumTags: ["B1"],
    description: "Students identify numbers on a simple number line."
  }
];

module.exports = kindergartenCatalog;