const PDFDocument = require("pdfkit");

function clamp(n, min, max) {
  if (Number.isNaN(n)) return min;
  return Math.max(min, Math.min(max, n));
}

function renderWorksheetPDF({ res, contentObject, options = {} }) {
  const { meta, content } = contentObject;
  const items = (content && content.items) ? content.items : [];

  const includeAnswerKey = options.includeAnswerKey !== false;
  const cols = clamp(parseInt(options.cols ?? 2, 10), 1, 3);
  const fontSize = clamp(parseInt(options.fontSize ?? 16, 10), 10, 28);

  // unique filename prevents macOS Preview caching confusion
  const safeMode = (meta.modeId || "worksheet").replace(/[^a-z0-9._-]/gi, "_");
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${safeMode}.pdf"`);

  const doc = new PDFDocument({
    size: "LETTER",
    margins: { top: 54, bottom: 54, left: 54, right: 54 },
    info: { Title: meta.title || "Worksheet", Author: "Yellowbird v1" },
  });

  doc.pipe(res);

  // ===== Page 1 =====
  doc.font("Helvetica-Bold").fontSize(18).text(meta.title || "Worksheet", { align: "center" });
  doc.moveDown(0.4);
  doc.font("Helvetica").fontSize(12).text(meta.subtitle || "", { align: "left" });
  doc.moveDown(1);

  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const colGap = cols === 1 ? 0 : cols === 2 ? 40 : 24;
  const rowGap = Math.round(fontSize * 2.1); // scales with font

  const colWidth = (pageWidth - colGap * (cols - 1)) / cols;
  const startX = doc.page.margins.left;
  const startY = doc.y;

  doc.font("Helvetica").fontSize(fontSize);

  for (let idx = 0; idx < items.length; idx++) {
    const it = items[idx];
    const c = idx % cols;
    const r = Math.floor(idx / cols);

    const x = startX + c * (colWidth + colGap);
    const y = startY + r * rowGap;

    doc.text(`${it.id})`, x, y, { width: 34, lineBreak: false });
    doc.text(it.prompt, x + 34, y, { width: colWidth - 34, lineBreak: false });

    const lineStartX = x + 34 + doc.widthOfString(it.prompt) + 10;
    const lineEndX = x + colWidth - 6;
    const lineY = y + Math.round(fontSize * 1.15);

    doc
      .moveTo(Math.min(lineStartX, lineEndX - 40), lineY)
      .lineTo(lineEndX, lineY)
      .stroke();
  }

  // Footer (safe inside margins)
  doc.fontSize(9).fillColor("#444");
  doc.text(
    "Generated by Yellowbird v1",
    doc.page.margins.left,
    doc.page.height - doc.page.margins.bottom - 12,
    { align: "left", lineBreak: false }
  );

  // ===== Page 2: Answer Key =====
  if (includeAnswerKey) {
    doc.addPage();

    doc.fillColor("#000");
    doc.font("Helvetica-Bold").fontSize(18).text(`${meta.title || "Worksheet"} — Answer Key`, { align: "center" });
    doc.moveDown(0.6);
    doc.font("Helvetica").fontSize(12).text(meta.subtitle || "", { align: "left" });
    doc.moveDown(1);

    const keyPageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const keyCols = 3;
    const keyColGap = 24;
    const keyRowGap = 18;

    const keyColWidth = (keyPageWidth - keyColGap * (keyCols - 1)) / keyCols;
    const keyStartX = doc.page.margins.left;
    const keyStartY = doc.y;

    doc.font("Helvetica").fontSize(12);

    for (let i = 0; i < items.length; i++) {
      const c = i % keyCols;
      const r = Math.floor(i / keyCols);

      const x = keyStartX + c * (keyColWidth + keyColGap);
      const y = keyStartY + r * keyRowGap;

      const it = items[i];
      doc.text(`${it.id})  ${it.prompt} ${it.answer}`, x, y, { width: keyColWidth, lineBreak: false });
    }

    doc.fontSize(9).fillColor("#444");
    doc.text(
      "Generated by Yellowbird v1",
      doc.page.margins.left,
      doc.page.height - doc.page.margins.bottom - 12,
      { align: "left", lineBreak: false }
    );
  }

  doc.end();
}

module.exports = { renderWorksheetPDF };